name       : gupnp
version    : 1.0.2
release    : 2
source     :
    - https://download.gnome.org/sources/gupnp/1.0/gupnp-1.0.2.tar.xz : 5173fda779111c6b01cd4a5e41b594322be9d04f8c74d3361f0a0c2069c77610
license    : LGPL-2.0
component  : network.util
summary    : GUPnP is an object-oriented open source framework for creating UPnP devices and control points.
description: |
    GUPnP is an object-oriented open source framework for creating UPnP devices and control points, written in C using GObject and libsoup. The GUPnP API is intended to be easy to use, efficient and flexible. It provides the same set of features as libupnp, but shields the developer from most of UPnP's internals.
builddeps  :
    - pkgconfig(gssdp-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
