name       : gupnp
version    : 1.0.3
release    : 4
source     :
    - https://download.gnome.org/sources/gupnp/1.0/gupnp-1.0.3.tar.xz : 794b162ee566d85eded8c3f3e8c9c99f6b718a6b812d8b56f0c2ed72ac37cbbb
license    : LGPL-2.0-only
component  : network.util
summary    : GUPnP is an object-oriented open source framework for creating UPnP devices and control points.
description: |
    GUPnP is an object-oriented open source framework for creating UPnP devices and control points, written in C using GObject and libsoup. The GUPnP API is intended to be easy to use, efficient and flexible. It provides the same set of features as libupnp, but shields the developer from most of UPnP's internals.
builddeps  :
    - pkgconfig(gssdp-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
